---
title: "GBM Proteomics - Patient summary"
author: "Miguel Cosenza-Contreras"
date: "`r Sys.Date()`"
format:
  gfm:
    toc: true 
    toc-depth: 4 # default is 3
    number-sections: true
    execute:
      output: true
always_allow_html: true
editor: source
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
```

# Required packages {.unnumbered .unlisted}

```{r}
library(readxl)
library(gtsummary)
library(here)
library(tidyverse)
library(flextable)
```

# Load and prep the data {.unnumbered .unlisted}

```{r echo=FALSE}
patient_table <- readxl::read_xlsx(path = here("data/Patients_information_FINAL.xlsx"))
```

```{r}
patients_proteomics <- patient_table %>%
  filter(`Mass Spectrometry` == "X") %>%
  dplyr::select(Sex, 
                `Age at surgery (years)`, 
                `Time-to-reccurence (days)`,
                `Type of resection`,
                `Tumor localization`, 
                Treatment,
                sample_id = `LAB-ID`) %>%
  mutate(`Time-to-reccurence (days)` = as.numeric(`Time-to-reccurence (days)`))
```

```{r}
patients_clinical <- patient_table %>%
  mutate(`Time-to-reccurence (days)` = as.numeric(`Time-to-reccurence (days)`),
         `Age at surgery (years)` = as.numeric(`Age at surgery (years)`),
         `Latency (days)` = as.numeric(`Latency (days)`)) %>% 
  pivot_longer(cols = c("Mass Spectrometry",
                        "Lipidomics",
                        "RT-qPCR",
                        "IHC",
                        "ELISA"),
               names_to = "Experiment",
               values_to = "X") %>%
  filter(!is.na(X)) %>%
  dplyr::select(-c(`LAB-ID`, Number))
```

```{r}
patients_clinical_min <- patients_clinical %>%
  dplyr::select(Sex, 
                `Age at surgery (years)`, 
                `Time-to-reccurence (days)`,
                `Latency (days)`,
                `Type of resection`,
                Experiment)
```

# Summary table of patients (minimal information)

```{r}
clin_tb_min <- tbl_summary(data = patients_clinical_min,
                           by = Experiment) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
```

```{r}
print(clin_tb_min)
```

```{r echo=FALSE}
clin_tb_min %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = here("suppl_tables/minimal_clinical_summary_table.docx"))
```

# Summary table of patients (all clinical information)

```{r}
tbl_summary(data = patients_clinical,
            by = Experiment) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
```

# Summary table of patients for proteomics

```{r}
tbl_summary(data = patients_proteomics) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
```
